export const cards = [
  {
    id: 1,
    title: "AI Artists",
    desc: "Add talent to AI",
    img: "./img/ai.jpg",
  },
  {
    id: 2,
    title: "Logo Design",
    desc: "Build yor brand",
    img: "./img/logodesign.jpg",
  },
  {
    id: 3,
    title: "WordPress",
    desc: "Customize your site",
    img: "./img/webdesign.jpg",
  },
  {
    id: 4,
    title: "Voice Over",
    desc: "Share your message",
    img: "./img/illustration.jpg",
  },
  {
    id: 5,
    title: "Video Explainer",
    desc: "Engage your audience",
    img: "./img/book.jpg",
  },
  {
    id: 6,
    title: "Social Media",
    desc: "Reach more customers",
    img: "./img/socialmedia.jpg",
  },
  {
    id: 7,
    title: "SEO",
    desc: "Unlock growth online",
    img: "./img/packaging.jpg",
  },
  {
    id: 8,
    title: "Illustration",
    desc: "Color you dreams",
    img: "./img/animated.jpg",
  },
];

export const projects = [
  {
    id: 1,
    img: "./img/webdesign.jpg",
    pp: "./img/madara.jpg",
    cat: "Web and Mobile Design",
    username: "Anchit Acharya",
  },
  {
    id: 2,
    img: "./img/logodesign.jpg",
    pp: "./img/eren.jpg",
    cat: "Logo Design",
    username: "Ayush Sharma",
  },
  {
    id: 3,
    img: "./img/animated.jpg",
    pp: "./img/naruto.jpg",
    cat: "Animated GIFs",
    username: "Ashish Sapkota",
  },
  {
    id: 4,
    img: "./img/packaging.jpg",
    pp: "./img/pain.jpg",
    cat: "Packaging Design",
    username: "Kabya Sharma",
  },
  {
    id: 5,
    img: "./img/socialmedia.jpg",
    pp: "./img/sasuke.jpg",
    cat: "Social Media Design",
    username: "Rashil khoju",
  },
  {
    id: 6,
    img: "./img/illustration.jpg",
    pp: "./img/aizen.jpg",
    cat: "Illustration",
    username: "Adhish Tiwari",
  },
  {
    id: 7,
    img: "./img/book.jpg",
    pp: "./img/gojo.jpg",
    cat: "Book Design",
    username: "Prince Gyawali",
  },
  {
    id: 8,
    img: "./img/digitalmarketing.jpg",
    pp: "./img/jiraiya.jpg",
    cat: "Digital Marketing",
    username: "Ashim Patel",
  },
];

export const gigs = [
  {
    id: 1,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/madara.jpg",
    desc: "I will create ai art character from your images and prompts",
    price: 59,
    star: 5,
    username: "Anchit Acharya",
  },
  {
    id: 2,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/eren.jpg",
    desc: "I will create ultra high quality character art with ai",
    price: 79,
    star: 5,
    username: "Ayush Sharma",
  },
  {
    id: 3,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/naruto.jpg",
    desc: "I will be creating unique ai generated artworks mid journey ai artist",
    price: 112,
    star: 5,
    username: "Ashish Sapkota",
  },
  {
    id: 4,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/pain.jpg",
    desc: "I will create custom ai generated artwork using your photos",
    price: 99,
    star: 4,
    username: "Kabya Sharma",
  },
  {
    id: 5,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/sasuke.jpg",
    desc: "I will recreate your dreams in high quality pictures",
    price: 59,
    star: 5,
    username: "Rashil Khoju",
  },
  {
    id: 6,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/aizen.jpg",
    desc: "I will create ai digital art illustration hyper realistic painting",
    price: 79,
    star: 4,
    username: "Adhish Tiwari",
  },
  {
    id: 7,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/gojo.jpg",
    desc: "I will generate images with your prompts using ai dalle",
    price: 89,
    star: 5,
    username: "Prince Gyawali",
  },
  {
    id: 8,
    img: "./img/aiartcharacter.jpg",
    pp: "./img/jiraiya.jpg",
    desc: "I will create custom art using midjourney generator",
    price: 110,
    star: 4,
    username: "Ashim Patel",
  },
];
